# Generated by Django 4.2.26 on 2025-12-01 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_init_roles_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='实例的显示名称，必须唯一', max_length=100, unique=True, verbose_name='实例别名')),
                ('host', models.CharField(help_text='MySQL 服务器的 IP 地址或域名', max_length=255, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=3306, help_text='MySQL 服务器的端口号', verbose_name='端口号')),
                ('username', models.CharField(help_text='连接 MySQL 的用户名', max_length=100, verbose_name='用户名')),
                ('password', models.TextField(help_text='加密存储的密码', verbose_name='密码')),
                ('description', models.TextField(blank=True, help_text='实例的详细说明', verbose_name='描述')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '错误')], default='offline', help_text='实例当前的运行状态', max_length=20, verbose_name='状态')),
                ('last_check_time', models.DateTimeField(blank=True, help_text='最后一次健康检查的时间', null=True, verbose_name='最后检查时间')),
                ('version', models.CharField(blank=True, help_text='MySQL 服务器版本号', max_length=50, verbose_name='MySQL 版本')),
                ('charset', models.CharField(default='utf8mb4', help_text='数据库默认字符集', max_length=50, verbose_name='字符集')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instances', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('team', models.ForeignKey(help_text='该实例所属的团队', on_delete=django.db.models.deletion.CASCADE, related_name='mysql_instances', to='authentication.team', verbose_name='所属团队')),
            ],
            options={
                'verbose_name': 'MySQL 实例',
                'verbose_name_plural': 'MySQL 实例',
                'db_table': 'mysql_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='指标采集的时间', verbose_name='时间戳')),
                ('qps', models.FloatField(default=0, help_text='Queries Per Second', verbose_name='每秒查询数')),
                ('tps', models.FloatField(default=0, help_text='Transactions Per Second', verbose_name='每秒事务数')),
                ('connections', models.IntegerField(default=0, help_text='当前活跃的数据库连接数', verbose_name='当前连接数')),
                ('slow_queries', models.IntegerField(default=0, help_text='慢查询的累计数量', verbose_name='慢查询数')),
                ('cpu_usage', models.FloatField(default=0, help_text='CPU 使用百分比', verbose_name='CPU 使用率')),
                ('memory_usage', models.FloatField(default=0, help_text='内存使用百分比', verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(default=0, help_text='磁盘使用百分比', verbose_name='磁盘使用率')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='instances.mysqlinstance', verbose_name='MySQL 实例')),
            ],
            options={
                'verbose_name': '监控指标',
                'verbose_name_plural': '监控指标',
                'db_table': 'mysql_monitoring_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='数据库的名称', max_length=100, verbose_name='数据库名称')),
                ('charset', models.CharField(default='utf8mb4', help_text='数据库字符集', max_length=50, verbose_name='字符集')),
                ('collation', models.CharField(default='utf8mb4_unicode_ci', help_text='数据库排序规则', max_length=50, verbose_name='排序规则')),
                ('size_mb', models.FloatField(default=0, help_text='数据库占用的磁盘空间大小', verbose_name='数据库大小(MB)')),
                ('table_count', models.IntegerField(default=0, help_text='数据库中的表数量', verbose_name='表数量')),
                ('last_backup_time', models.DateTimeField(blank=True, help_text='最后一次成功备份的时间', null=True, verbose_name='最后备份时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='instances.mysqlinstance', verbose_name='MySQL 实例')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
                'db_table': 'mysql_database',
                'ordering': ['instance', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='mysqlinstance',
            index=models.Index(fields=['team'], name='idx_instance_team'),
        ),
        migrations.AddIndex(
            model_name='mysqlinstance',
            index=models.Index(fields=['status'], name='idx_instance_status'),
        ),
        migrations.AddIndex(
            model_name='mysqlinstance',
            index=models.Index(fields=['alias'], name='idx_instance_alias'),
        ),
        migrations.AddIndex(
            model_name='monitoringmetrics',
            index=models.Index(fields=['instance', '-timestamp'], name='idx_metrics_instance_time'),
        ),
        migrations.AddIndex(
            model_name='database',
            index=models.Index(fields=['instance', 'name'], name='idx_db_instance_name'),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('instance', 'name')},
        ),
    ]
