# Generated by Django 4.2.27 on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlinstance',
            name='deployment_type',
            field=models.CharField(choices=[('docker', 'Docker容器'), ('systemd', '系统服务')], default='systemd', help_text='MySQL 实例运行方式（Docker 容器或系统服务）', max_length=20, verbose_name='部署方式'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='docker_container_name',
            field=models.CharField(blank=True, help_text='Docker 部署时的容器名称', max_length=200, verbose_name='容器名称'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='mysql_service_name',
            field=models.CharField(default='mysql', help_text='系统服务名称（systemd），如 mysql 或 mysqld', max_length=200, verbose_name='服务名称'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='data_dir',
            field=models.CharField(blank=True, help_text='MySQL 数据目录（用于冷备/热备物理备份）', max_length=500, verbose_name='数据目录'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='执行备份命令的远程主机地址', max_length=255, verbose_name='SSH 主机'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22, help_text='SSH 连接端口', verbose_name='SSH 端口'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='ssh_user',
            field=models.CharField(blank=True, help_text='SSH 用户名', max_length=100, verbose_name='SSH 用户'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='ssh_password',
            field=models.TextField(blank=True, help_text='加密存储的 SSH 密码', verbose_name='SSH 密码'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='ssh_key_path',
            field=models.CharField(blank=True, help_text='SSH 私钥路径（优先于密码）', max_length=500, verbose_name='SSH 私钥路径'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='xtrabackup_bin',
            field=models.CharField(default='xtrabackup', help_text='xtrabackup 可执行文件路径或命令名', max_length=300, verbose_name='XtraBackup 路径'),
        ),
    ]
