# Generated by Django 4.2.26 on 2025-12-01 07:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='11位手机号码', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, help_text='用户头像的 URL 地址', max_length=500, null=True, verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用户账户创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='用户信息最后更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='权限的显示名称，如"查看实例"', max_length=100, verbose_name='权限名称')),
                ('slug', models.SlugField(help_text='权限的唯一标识符，如"view_instance"', max_length=100, unique=True, verbose_name='权限标识')),
                ('category', models.CharField(choices=[('user', '用户管理'), ('team', '团队管理'), ('instance', '实例管理'), ('backup', '备份管理'), ('sql', 'SQL执行'), ('monitoring', '监控管理'), ('system', '系统管理')], default='system', help_text='权限所属的功能分类', max_length=20, verbose_name='权限分类')),
                ('description', models.TextField(blank=True, help_text='详细说明该权限的作用和范围', verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'auth_custom_permission',
                'ordering': ['category', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色的显示名称，如"超级管理员"', max_length=50, unique=True, verbose_name='角色名称')),
                ('slug', models.SlugField(help_text='角色的唯一标识符，如"super_admin"', unique=True, verbose_name='角色标识')),
                ('description', models.TextField(blank=True, help_text='详细说明该角色的职责和权限范围', verbose_name='角色描述')),
                ('is_builtin', models.BooleanField(default=False, help_text='内置角色不可删除，只能修改权限', verbose_name='内置角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permissions', models.ManyToManyField(blank=True, help_text='该角色拥有的所有权限', related_name='roles', to='authentication.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'auth_role',
                'ordering': ['-is_builtin', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='团队的显示名称', max_length=100, unique=True, verbose_name='团队名称')),
                ('description', models.TextField(blank=True, help_text='团队的简介和用途说明', verbose_name='团队描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
                'db_table': 'auth_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='用户加入团队的时间', verbose_name='加入时间')),
                ('role', models.ForeignKey(help_text='用户在该团队中的角色', on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='authentication.role', verbose_name='角色')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.team', verbose_name='团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'db_table': 'auth_team_member',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='团队的所有成员用户', related_name='teams', through='authentication.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(help_text='创建并拥有该团队的用户，不能删除', on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='团队所有者'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['slug'], name='idx_permission_slug'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['category'], name='idx_permission_category'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user', 'team'], name='idx_tm_user_team'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'role'], name='idx_tm_team_role'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('user', 'team')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='idx_team_name'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner'], name='idx_team_owner'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['slug'], name='idx_role_slug'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_builtin'], name='idx_role_builtin'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='idx_user_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='idx_user_phone'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_active'),
        ),
    ]
