# Generated by Django 4.2.26 on 2025-12-01 08:01

from django.db import migrations


def create_permissions(apps, schema_editor):
    """创建系统内置权限"""
    Permission = apps.get_model('authentication', 'Permission')
    
    # 定义所有权限
    permissions_data = [
        # 用户管理类权限
        {'name': '管理用户', 'slug': 'manage_users', 'category': 'user', 'description': '创建、编辑、删除用户账户'},
        {'name': '查看用户', 'slug': 'view_users', 'category': 'user', 'description': '查看用户列表和详细信息'},
        
        # 团队管理类权限
        {'name': '管理团队', 'slug': 'manage_teams', 'category': 'team', 'description': '创建、编辑、删除团队'},
        {'name': '查看团队', 'slug': 'view_teams', 'category': 'team', 'description': '查看团队列表和详细信息'},
        {'name': '管理团队成员', 'slug': 'manage_team_members', 'category': 'team', 'description': '添加、移除团队成员，分配角色'},
        
        # 实例管理类权限
        {'name': '管理实例', 'slug': 'manage_instances', 'category': 'instance', 'description': '创建、编辑、删除数据库实例配置'},
        {'name': '查看实例', 'slug': 'view_instances', 'category': 'instance', 'description': '查看数据库实例列表和详细信息'},
        {'name': '连接实例', 'slug': 'connect_instance', 'category': 'instance', 'description': '建立与数据库实例的连接'},
        
        # 备份管理类权限
        {'name': '创建备份', 'slug': 'create_backup', 'category': 'backup', 'description': '手动创建数据库备份任务'},
        {'name': '恢复备份', 'slug': 'restore_backup', 'category': 'backup', 'description': '从备份恢复数据库'},
        {'name': '查看备份', 'slug': 'view_backups', 'category': 'backup', 'description': '查看备份历史和详细信息'},
        {'name': '删除备份', 'slug': 'delete_backup', 'category': 'backup', 'description': '删除备份文件'},
        {'name': '配置备份策略', 'slug': 'configure_backup_policy', 'category': 'backup', 'description': '配置自动备份策略和计划任务'},
        
        # SQL执行类权限
        {'name': '执行SQL查询', 'slug': 'execute_sql_query', 'category': 'sql', 'description': '执行SELECT等查询语句'},
        {'name': '执行SQL修改', 'slug': 'execute_sql_modify', 'category': 'sql', 'description': '执行INSERT、UPDATE、DELETE等修改语句'},
        {'name': '执行DDL语句', 'slug': 'execute_ddl', 'category': 'sql', 'description': '执行CREATE、ALTER、DROP等DDL语句'},
        {'name': '导出查询结果', 'slug': 'export_results', 'category': 'sql', 'description': '导出SQL查询结果为文件'},
        
        # 监控管理类权限
        {'name': '查看监控数据', 'slug': 'view_monitoring', 'category': 'monitoring', 'description': '查看数据库性能监控数据'},
        {'name': '配置监控告警', 'slug': 'configure_alerts', 'category': 'monitoring', 'description': '配置监控告警规则'},
        
        # 系统管理类权限
        {'name': '系统配置管理', 'slug': 'manage_system_config', 'category': 'system', 'description': '修改系统全局配置'},
        {'name': '查看系统日志', 'slug': 'view_system_logs', 'category': 'system', 'description': '查看系统操作日志'},
    ]
    
    # 批量创建权限
    for perm_data in permissions_data:
        Permission.objects.get_or_create(
            slug=perm_data['slug'],
            defaults=perm_data
        )


def create_roles(apps, schema_editor):
    """创建系统内置角色并分配权限"""
    Role = apps.get_model('authentication', 'Role')
    Permission = apps.get_model('authentication', 'Permission')
    
    # 1. 超级管理员 - 拥有所有权限
    super_admin, created = Role.objects.get_or_create(
        slug='super_admin',
        defaults={
            'name': '超级管理员',
            'description': '拥有系统所有权限，可以管理用户、团队、实例、备份等所有功能',
            'is_builtin': True,
        }
    )
    if created:
        # 分配所有权限
        all_permissions = Permission.objects.all()
        super_admin.permissions.set(all_permissions)
    
    # 2. 团队管理员 - 管理团队和团队资源
    team_admin, created = Role.objects.get_or_create(
        slug='team_admin',
        defaults={
            'name': '团队管理员',
            'description': '管理团队成员、团队内的数据库实例和备份，但不能管理其他团队',
            'is_builtin': True,
        }
    )
    if created:
        team_admin_perms = Permission.objects.filter(
            slug__in=[
                'view_teams', 'manage_team_members',
                'manage_instances', 'view_instances', 'connect_instance',
                'create_backup', 'restore_backup', 'view_backups', 'delete_backup', 'configure_backup_policy',
                'execute_sql_query', 'execute_sql_modify', 'export_results',
                'view_monitoring', 'configure_alerts',
            ]
        )
        team_admin.permissions.set(team_admin_perms)
    
    # 3. 开发人员 - 日常开发和查询
    developer, created = Role.objects.get_or_create(
        slug='developer',
        defaults={
            'name': '开发人员',
            'description': '查看实例和备份、执行SQL查询、导出数据、查看监控，但不能修改配置或执行危险操作',
            'is_builtin': True,
        }
    )
    if created:
        developer_perms = Permission.objects.filter(
            slug__in=[
                'view_instances', 'connect_instance',
                'view_backups',
                'execute_sql_query', 'export_results',
                'view_monitoring',
            ]
        )
        developer.permissions.set(developer_perms)
    
    # 4. 运维人员 - 备份和监控管理
    operator, created = Role.objects.get_or_create(
        slug='operator',
        defaults={
            'name': '运维人员',
            'description': '管理备份、查看监控、配置告警，但不能执行SQL或管理用户',
            'is_builtin': True,
        }
    )
    if created:
        operator_perms = Permission.objects.filter(
            slug__in=[
                'view_instances',
                'create_backup', 'restore_backup', 'view_backups', 'delete_backup', 'configure_backup_policy',
                'view_monitoring', 'configure_alerts',
                'view_system_logs',
            ]
        )
        operator.permissions.set(operator_perms)
    
    # 5. 只读用户 - 仅查看权限
    viewer, created = Role.objects.get_or_create(
        slug='viewer',
        defaults={
            'name': '只读用户',
            'description': '仅能查看实例、备份和监控信息，不能执行任何操作',
            'is_builtin': True,
        }
    )
    if created:
        viewer_perms = Permission.objects.filter(
            slug__in=[
                'view_instances',
                'view_backups',
                'view_monitoring',
            ]
        )
        viewer.permissions.set(viewer_perms)


def reverse_init(apps, schema_editor):
    """回滚操作：删除所有内置角色和权限"""
    Role = apps.get_model('authentication', 'Role')
    Permission = apps.get_model('authentication', 'Permission')
    
    # 删除内置角色
    Role.objects.filter(is_builtin=True).delete()
    
    # 删除所有权限（如果需要保留自定义权限，可以添加过滤条件）
    Permission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_init),
        migrations.RunPython(create_roles, migrations.RunPython.noop),
    ]
