# Generated by Django 4.2.26 on 2025-12-01 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='备份策略的显示名称', max_length=100, verbose_name='策略名称')),
                ('databases', models.JSONField(blank=True, help_text='要备份的数据库列表，为空表示备份所有数据库', null=True, verbose_name='数据库列表')),
                ('cron_expression', models.CharField(help_text='备份执行的 Cron 表达式，如 "0 2 * * *" 表示每天凌晨2点', max_length=100, verbose_name='Cron 表达式')),
                ('backup_type', models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份')], default='full', help_text='备份类型：全量或增量', max_length=20, verbose_name='备份类型')),
                ('retention_days', models.IntegerField(default=7, help_text='备份文件保留的天数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='保留天数')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用该备份策略', verbose_name='是否启用')),
                ('storage_path', models.CharField(blank=True, help_text='备份文件的存储路径，为空则使用默认路径', max_length=500, verbose_name='存储路径')),
                ('compress', models.BooleanField(default=True, help_text='是否压缩备份文件', verbose_name='是否压缩')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_strategies', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('instance', models.ForeignKey(help_text='要备份的 MySQL 实例', on_delete=django.db.models.deletion.CASCADE, related_name='backup_strategies', to='instances.mysqlinstance', verbose_name='MySQL 实例')),
            ],
            options={
                'verbose_name': '备份策略',
                'verbose_name_plural': '备份策略',
                'db_table': 'backup_strategy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(blank=True, help_text='备份的数据库名称，为空表示全实例备份', max_length=100, verbose_name='数据库名称')),
                ('backup_type', models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份')], default='full', help_text='备份类型：全量或增量', max_length=20, verbose_name='备份类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', help_text='备份任务的执行状态', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, help_text='备份文件的完整路径', max_length=500, verbose_name='文件路径')),
                ('file_size_mb', models.FloatField(default=0, help_text='备份文件的大小（MB）', verbose_name='文件大小(MB)')),
                ('start_time', models.DateTimeField(blank=True, help_text='备份任务开始的时间', null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='备份任务结束的时间', null=True, verbose_name='结束时间')),
                ('error_message', models.TextField(blank=True, help_text='备份失败时的错误详情', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='手动触发备份的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_records', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('instance', models.ForeignKey(help_text='备份的 MySQL 实例', on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='instances.mysqlinstance', verbose_name='MySQL 实例')),
                ('strategy', models.ForeignKey(blank=True, help_text='关联的备份策略，手动备份时为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_records', to='backups.backupstrategy', verbose_name='备份策略')),
            ],
            options={
                'verbose_name': '备份记录',
                'verbose_name_plural': '备份记录',
                'db_table': 'backup_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backupstrategy',
            index=models.Index(fields=['instance'], name='idx_strategy_instance'),
        ),
        migrations.AddIndex(
            model_name='backupstrategy',
            index=models.Index(fields=['is_enabled'], name='idx_strategy_enabled'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['instance', 'status'], name='idx_record_instance_status'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['instance', '-start_time'], name='idx_record_instance_time'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['status'], name='idx_record_status'),
        ),
    ]
