# Generated by Django 4.2.27 on 2026-01-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupstrategy',
            name='backup_type',
            field=models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份'), ('hot', '热备份'), ('cold', '冷备份')], default='full', help_text='备份类型：全量或增量', max_length=20, verbose_name='备份类型'),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份'), ('hot', '热备份'), ('cold', '冷备份')], default='full', help_text='备份类型：全量或增量', max_length=20, verbose_name='备份类型'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='base_backup',
            field=models.ForeignKey(blank=True, help_text='增量备份的基准备份记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incremental_children', to='backups.backuprecord', verbose_name='基准备份'),
        ),
    ]
