# Generated by Django 4.2.27 on 2026-01-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backup_types_and_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份'), ('hot', '热备份'), ('cold', '冷备份')], default='full', help_text='备份类型：全量、增量、热备或冷备', max_length=20, verbose_name='备份类型'),
        ),
        migrations.AlterField(
            model_name='backupstrategy',
            name='backup_type',
            field=models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份'), ('hot', '热备份'), ('cold', '冷备份')], default='full', help_text='备份类型：全量、增量、热备或冷备', max_length=20, verbose_name='备份类型'),
        ),
    ]
