# Generated by Django 4.2.27 on 2026-01-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0008_storage_modes_and_remote_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreBoard',
            fields=[
            ],
            options={
                'verbose_name': '备份恢复',
                'verbose_name_plural': '备份恢复',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backups.backuprecord',),
        ),
        migrations.CreateModel(
            name='BackupTaskBoard',
            fields=[
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backups.backuprecord',),
        ),
    ]
