# Generated by Django 4.2.26 on 2025-12-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(blank=True, help_text='执行查询的数据库名称，为空表示未指定数据库', max_length=100, verbose_name='数据库名称')),
                ('sql_statement', models.TextField(help_text='执行的 SQL 语句原文', verbose_name='SQL 语句')),
                ('sql_type', models.CharField(choices=[('SELECT', '查询'), ('INSERT', '插入'), ('UPDATE', '更新'), ('DELETE', '删除'), ('DDL', '数据定义'), ('SHOW', '显示'), ('DESC', '描述'), ('EXPLAIN', '解释'), ('OTHER', '其他')], default='OTHER', help_text='SQL 语句的类型', max_length=20, verbose_name='SQL 类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='success', help_text='SQL 执行的状态', max_length=20, verbose_name='执行状态')),
                ('rows_affected', models.IntegerField(default=0, help_text='SQL 执行影响的行数（INSERT/UPDATE/DELETE）或返回的行数（SELECT）', verbose_name='影响行数')),
                ('execution_time_ms', models.IntegerField(default=0, help_text='SQL 执行所用的时间，单位为毫秒', verbose_name='执行时间(毫秒)')),
                ('error_message', models.TextField(blank=True, help_text='SQL 执行失败时的错误信息', verbose_name='错误信息')),
                ('result_cached', models.BooleanField(default=False, help_text='查询结果是否已缓存到 Redis', verbose_name='结果已缓存')),
                ('result_cache_key', models.CharField(blank=True, help_text='Redis 中存储结果的缓存键', max_length=255, verbose_name='结果缓存键')),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='SQL 执行的时间戳', verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(help_text='执行该 SQL 的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sql_queries', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('instance', models.ForeignKey(help_text='执行查询的 MySQL 实例', on_delete=django.db.models.deletion.CASCADE, related_name='query_histories', to='instances.mysqlinstance', verbose_name='MySQL 实例')),
            ],
            options={
                'verbose_name': 'SQL 执行历史',
                'verbose_name_plural': 'SQL 执行历史',
                'db_table': 'sqlclient_query_history',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['instance', 'executed_by', '-executed_at'], name='idx_qh_inst_user_time'), models.Index(fields=['instance', '-executed_at'], name='idx_qh_inst_time'), models.Index(fields=['executed_by', '-executed_at'], name='idx_qh_user_time'), models.Index(fields=['status'], name='idx_qh_status'), models.Index(fields=['sql_type'], name='idx_qh_sql_type')],
            },
        ),
    ]
